# Generated by Django 2.2.7 on 2020-01-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', editable=False)),
                ('first_name', models.CharField(default='not known yet', max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('X', 'not yet known')], default='X', max_length=1)),
                ('start_date', models.DateField()),
                ('care_time', models.CharField(choices=[('F', 'full time'), ('M', 'morning'), ('A', 'afternoon')], default='F', max_length=1)),
                ('contact_email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=128)),
                ('zip', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(default='DE', max_length=2)),
                ('first_name_father', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name_father', models.CharField(blank=True, max_length=128, null=True)),
                ('profession_father', models.CharField(blank=True, max_length=128, null=True)),
                ('email_father', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_father', models.CharField(blank=True, max_length=32, null=True)),
                ('nationality_father', models.CharField(default='DE', max_length=2)),
                ('first_name_mother', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name_mother', models.CharField(blank=True, max_length=128, null=True)),
                ('profession_mother', models.CharField(blank=True, max_length=128, null=True)),
                ('email_mother', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_mother', models.CharField(blank=True, max_length=32, null=True)),
                ('nationality_mother', models.CharField(default='DE', max_length=2)),
                ('remark', models.TextField(default='.', max_length=1024)),
                ('urgency', models.CharField(choices=[('A', 'Kinder aus Familien, die gemäß §27 i.V.m.§36 SGB VIII der „Hilfe zur Erziehung“ bedürfen'), ('B', 'Kinder, deren Mutter oder Vater alleinerziehend und berufstätig oder in Ausbildung ist, sowie Kinder \n                 deren beide Elternteile berufstätig oder in Ausbildung sind, soweit Umfang und Lage der Arbeitszeit \n                 bzw. Unterrichtszeit die Betreuung erforderlich machen'), ('C', 'Soziale Härtefälle')], default='A', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expiry_extension', models.DateField(blank=True, null=True)),
                ('expiry_comment', models.CharField(default='inital 6 months', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSendPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
