# Generated by Django 2.2.7 on 2020-02-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_streampage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='link_bottom',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_text_bottom',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_text_top',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link_top',
        ),
    ]
