# Generated by Django 2.2.7 on 2020-01-08 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWeekAdmin',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.FloatField(default=8.0)),
                ('tuesday', models.FloatField(default=8.0)),
                ('wednesday', models.FloatField(default=8.0)),
                ('thursday', models.FloatField(default=8.0)),
                ('friday', models.FloatField(default=8.0)),
                ('week', models.DateField(default=django.utils.timezone.now)),
                ('booked', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updator', to=settings.AUTH_USER_MODEL)),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=TabError)),
                ('holidays_per_year', models.FloatField(default=30.0)),
                ('hours_monday', models.FloatField(default=8.0)),
                ('hours_tuesday', models.FloatField(default=8.0)),
                ('hours_wednesday', models.FloatField(default=8.0)),
                ('hours_thursday', models.FloatField(default=8.0)),
                ('hours_friday', models.FloatField(default=8.0)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
