# Generated by Django 2.2.7 on 2020-01-23 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetrack', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkWeekAdmin',
            new_name='WorkWeekAdminPage',
        ),
    ]
