# Generated by Django 2.2.7 on 2020-01-08 15:30

from django.conf import settings
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('joyous', '0015_auto_20190409_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceSendPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GirotondoCalendar',
            fields=[
                ('calendarpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='joyous.CalendarPage')),
            ],
            options={
                'verbose_name': 'Girotondo Calendar',
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, 'joyous.calendarpage'),
        ),
        migrations.CreateModel(
            name='HolidaySendPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='not known yet', max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('X', 'not yet known')], default='X', max_length=1)),
                ('care_time', models.CharField(choices=[('F', 'full time'), ('M', 'morning'), ('A', 'afternoon')], default='F', max_length=1)),
                ('care_group', models.CharField(choices=[('P', 'piccoli'), ('M', 'medi'), ('G', 'grandi'), ('N', 'none')], default='P', max_length=1)),
                ('contact_email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=128)),
                ('zip', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(default='DE', max_length=2)),
                ('remark', models.TextField(blank=True, null=True)),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('remark', models.CharField(default='Urlaub', max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted_on', models.DateTimeField(auto_now=True)),
                ('child_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Child')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
